<?php

namespace Marlene\ActasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActasRepository extends EntityRepository
{
}
