<?php

namespace Marlene\ActasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JuzgadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuzgadoRepository extends EntityRepository
{
}
