marlene_actas:
    resource: "@MarleneActasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_user_bundle:
    resource: "@UserBundle/Resources/Config/routing.yml"