parameters:
#    marlene_actas.example.class: Marlene\ActasBundle\Example

services:
#    marlene_actas.example:
#        class: %marlene_actas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
