Marlene\ActasBundle\Entity\Abogado:
    properties:
        cUIT:
            - Range:
                min: 100000000000
                max: 999999999999
                minMessage: El cuit ser mayor a {{ limit }}
                maxMessage: El cuit debe ser menor a {{ limit }}

